id: e16a2c2e-09bf-4607-82c2-f249f9dcf5fe
version: 1
name: Fidelis Elevate Endpoint Execute Script
description: This script will obtain a list of available scripts and their options.
  It will then present the user with an option of which script can be executed and
  the answers that are required.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d61a84a6-c72b-4a1d-8f76-c66ca2f18797
    type: start
    task:
      id: d61a84a6-c72b-4a1d-8f76-c66ca2f18797
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: e8b1b008-641c-47b0-8cd2-f83aca62468a
    type: regular
    task:
      id: e8b1b008-641c-47b0-8cd2-f83aca62468a
      version: -1
      name: Get a list of tasks that are available
      script: FidelisElevateEndpointGetScripts
      type: regular
      iscommand: false
      brand: Fidelis Elevate Endpoint
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 5ee34b3b-db10-49f5-845c-7cf1be868f82
    type: collection
    task:
      id: 5ee34b3b-db10-49f5-845c-7cf1be868f82
      version: -1
      name: Select Script
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Fidelis Analyst
      subject:
        simple: Select a task
      body:
        complex:
          root: Fidelis
          accessor: Endpoint.Scripts
          transformers:
          - operator: join
            args:
              separator:
                value:
                  simple: |2+

          - operator: concat
            args:
              prefix:
                value:
                  simple: "Please use the name of one of the scripts below to execute:\n
                    \n "
              suffix:
                value:
                  simple: " \n \nYou will need to paste the value using the link below.."
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Please enter the script name to run or "None" to stop running scripts
        required: true
        gridcolumns: []
        defaultrows: []
        type: shortText
        options:
        - "Yes"
        - "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: Use "None" to stop executing scripts
      title: Select Script to Run
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
  "6":
    id: "6"
    taskid: 14011624-c2b7-4bcd-8f4e-85ea9921de0f
    type: regular
    task:
      id: 14011624-c2b7-4bcd-8f4e-85ea9921de0f
      version: -1
      name: FidelisElevateEndpointExecuteScript
      script: FidelisElevateEndpointExecuteScript
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      hostname:
        simple: ${incident.endpointname}
      scriptname:
        simple: ${Select Script to Run.Answers.0}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 98808f5a-13ad-4fdf-803a-cd617089e66e
    type: regular
    task:
      id: 98808f5a-13ad-4fdf-803a-cd617089e66e
      version: -1
      name: Set no more scripts flag
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsComplete
      value:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: f55d4a9f-fba9-4b0a-814b-2579e53397b9
    type: condition
    task:
      id: f55d4a9f-fba9-4b0a-814b-2579e53397b9
      version: -1
      name: Check no more scripts
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      None:
      - "7"
    separatecontext: false
    conditions:
    - label: None
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Fidelis.Endpoint.Alert.ScriptsCurrent
            iscontext: true
          right:
            value:
              simple: None
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 744ffd15-59c3-4d6f-8ca8-2ecef75e2df3
    type: regular
    task:
      id: 744ffd15-59c3-4d6f-8ca8-2ecef75e2df3
      version: -1
      name: Set script name
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsCurrent
      value:
        simple: ${Select Script to Run.Answers.0}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs:
- contextPath: Fidelis.Endpoint.Alert.ScriptsComplete
  type: unknown
