id: e7ac9021-96ee-451c-88fa-a2a027f5f20b
version: 19
name: Fidelis Elevate Endpoint Enrichment
description: This playbook will attempt to gather event data for the alert (if it
  exists and the alert does not already have event data). It will also assign an incident
  type based on the event data it finds.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 112a7fbb-5815-4097-8c40-9e3ee37c7d44
    type: start
    task:
      id: 112a7fbb-5815-4097-8c40-9e3ee37c7d44
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1880,
          "y": 100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 0c7dd363-77a0-44f9-8c62-d26301ddce0d
    type: condition
    task:
      id: 0c7dd363-77a0-44f9-8c62-d26301ddce0d
      version: -1
      name: Is there an alert ID?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "86"
      "yes":
      - "66"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: incident.fidelisendpointalertid
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1880,
          "y": 250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: d93433c3-631a-40a3-854d-d24c85410e3a
    type: title
    task:
      id: d93433c3-631a-40a3-854d-d24c85410e3a
      version: -1
      name: Populate incident fields
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "83"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1070,
          "y": 900
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "66":
    id: "66"
    taskid: 29436b9b-37b9-44f7-81e6-618378b5eb9e
    type: regular
    task:
      id: 29436b9b-37b9-44f7-81e6-618378b5eb9e
      version: -1
      name: Get Alert Details
      description: Retrieves the details of an alert
      scriptName: FidelisElevateEndpointGetAlertDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "82"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "70":
    id: "70"
    taskid: 762a121b-8672-4d1e-8403-4f6c22bc42ad
    type: regular
    task:
      id: 762a121b-8672-4d1e-8403-4f6c22bc42ad
      version: -1
      name: Get Endpoint Details
      description: Attempts to refresh the endpoint details associated with the incident
      scriptName: FidelisElevateEndpointRefreshEndpointDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "87"
    scriptarguments:
      hostname:
        simple: ${incident.endpointname}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "71":
    id: "71"
    taskid: 0e955740-d1d8-4791-8fc8-8fff61b263ee
    type: playbook
    task:
      id: 0e955740-d1d8-4791-8fc8-8fff61b263ee
      version: -1
      name: Fidelis Elevate Endpoint Get Event for Alert
      description: Attempts to look up the event data associated with an alert generated
        by Fidelis Elevate Endpoint
      playbookName: Fidelis Elevate Endpoint Get Event for Alert
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
      sleepTime:
        simple: "5"
    separatecontext: false
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: Fidelis.Endpoint.Alert.Event Found
            iscontext: true
          right:
            value:
              simple: "True"
        - operator: greaterThanOrEqual
          left:
            value:
              simple: Fidelis.Endpoint.Alert.Event Retries
            iscontext: true
          right:
            value:
              simple: "5"
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "72":
    id: "72"
    taskid: 4abd76b5-2b18-43fe-83f1-9f3fa2f18924
    type: regular
    task:
      id: 4abd76b5-2b18-43fe-83f1-9f3fa2f18924
      version: -1
      name: Set the event collect retry count to 0
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "71"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.Event Retries
      value:
        simple: "0"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "82":
    id: "82"
    taskid: a92f1ed3-bbc5-4c19-8354-f3f45cfb6aff
    type: regular
    task:
      id: a92f1ed3-bbc5-4c19-8354-f3f45cfb6aff
      version: -1
      name: Get Platform Details
      scriptName: FidelisElevateEndpointGetPlatformDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "70"
    reputationcalc: 1
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "83":
    id: "83"
    taskid: 1ac3baf1-2e79-4ddf-89a3-eee0044441bb
    type: regular
    task:
      id: 1ac3baf1-2e79-4ddf-89a3-eee0044441bb
      version: -1
      name: Populate incident fields
      scriptName: FidelisElevateEndpointIncidentFields
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "86"
    reputationcalc: 2
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1070,
          "y": 1050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "86":
    id: "86"
    taskid: 836dc8a2-283a-47ff-885f-961cf8b550f8
    type: title
    task:
      id: 836dc8a2-283a-47ff-885f-961cf8b550f8
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1730,
          "y": 1440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "87":
    id: "87"
    taskid: 3697b104-4245-4049-8a36-5d7a979fe31a
    type: condition
    task:
      id: 3697b104-4245-4049-8a36-5d7a979fe31a
      version: -1
      name: Is the alert from vulnerable software alert?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "72"
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: incident.labels.Source
            iscontext: true
          right:
            value:
              simple: Installed Software CVE
    - label: "no"
      condition:
      - - operator: isNotEqualString
          left:
            value:
              simple: incident.labels.Source
            iscontext: true
          right:
            value:
              simple: Installed Software CVE
    view: |-
      {
        "position": {
          "x": 430,
          "y": 580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 1830,
        "x": 430,
        "y": 100
      }
    }
  }
inputs: []
outputs: []
