commonfields:
  id: a41755e5-322f-4792-810f-beb6e25e1945
  version: 2
name: FidelisElevateEndpointExecutePlaybook
script: |
  #####################
  # Get hostname
  #####################
  hostname = None
  try:
      hostname = demisto.args()["hostname"]
  except:
      hostname = None
  if hostname is None:
      hostname = demisto.get(demisto.context(), "Fidelis.Endpoint.Alert.Target")

  ##############
  # Get playbook
  ##############
  playbook = None
  try:
      playbook = demisto.args()["playbook"]
  except:
      pass

  ##############
  # Get timeout
  ##############
  timeout = None
  try:
      timeout = demisto.args()["timeout"]
  except:
      pass

  #######################
  # Execute the playbook
  #######################
  demisto.results(demisto.executeCommand("fidelis-edr-execute-playbook", {"hostname": hostname, "playbook": playbook, "timeout": timeout }))
type: python
tags: []
comment: Execute a Fidelis Elevate Endpoint Playbook on an endpoint
enabled: true
args:
- name: hostname
  description: Host Name to target
- name: playbook
  description: Playbook to execute
- name: timeout
  description: Timeout to wait for the job to complete (default is 30 seconds)
  defaultValue: "30"
scripttarget: 0
subtype: python3
runonce: false
runas: DBotWeakRole
