id: 68bb9ab1-a72e-446d-8023-72f73b25d063
version: 50
name: Fidelis Elevate Endpoint - Default Playbook
description: This is the default playbook for Fidelis Elevate Endpoint Incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
    type: start
    task:
      id: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: fd32ea2b-15fd-4e54-8048-93be5c241a9a
    type: playbook
    task:
      id: fd32ea2b-15fd-4e54-8048-93be5c241a9a
      version: -1
      name: Fidelis Elevate Endpoint Enrichment
      description: This playbook will attempt to gather event data for the alert (if
        it exists and the alert does not already have event data). It will also assign
        an incident type based on the event data it finds.
      playbookName: Fidelis Elevate Endpoint Enrichment
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
    type: title
    task:
      id: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 60fdf69a-4c5b-49f7-828e-15b684e8aae8
    type: playbook
    task:
      id: 60fdf69a-4c5b-49f7-828e-15b684e8aae8
      version: -1
      name: Fidelis Elevate Endpoint Script - Isolate Endpoint
      description: This script will request authorisation to execute an endpoint isolation
        script using Fidelis Elevate Endpoint
      playbookName: Fidelis Elevate Endpoint Script - Isolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      justification: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 95afeafc-81b9-41db-8644-4f6d983ff9a4
    type: regular
    task:
      id: 95afeafc-81b9-41db-8644-4f6d983ff9a4
      version: -1
      name: Run Process List Script
      description: Attempts to retrieve the live running processes from an endpoint.
      scriptName: FidelisElevateEndpointGetRunningProcesses
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      filter:
        simple: ${lastCompletedTaskEntries.[0]}
      hostname:
        simple: ${incident.endpointname}
      updateContext: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: c03ea329-e256-49fe-85d2-144b210b5f90
    type: condition
    task:
      id: c03ea329-e256-49fe-85d2-144b210b5f90
      version: -1
      name: Investigate
      description: |-
        # Investigate

        All tasks as part of this incidents playbook have been completed.

        When this task is completed the incident will close.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Complete:
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: e10c55bb-feec-47e3-87c0-cc30685f7df6
    type: regular
    task:
      id: e10c55bb-feec-47e3-87c0-cc30685f7df6
      version: -1
      name: Close Incident
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id:
        simple: ${incident.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: a1cf3e20-1db1-4980-82b9-6a49d0e7440a
    type: condition
    task:
      id: a1cf3e20-1db1-4980-82b9-6a49d0e7440a
      version: -1
      name: Delete Fidelis Alert?
      description: |-
        # Delete Fidelis Alert

        Please select whether you would like to delete the alert from the FIdelis Elevate Endpoint Platform.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      DO NOT delete:
      - "14"
      Delete:
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 87125a20-b1f9-4390-8c1f-61511dd79d62
    type: regular
    task:
      id: 87125a20-b1f9-4390-8c1f-61511dd79d62
      version: -1
      name: FidelisElevateEndpointDeleteAlert
      description: Attempts to delete an alert from the Fidelis Endpoint Platform
      scriptName: FidelisElevateEndpointDeleteAlert
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 987cbeb0-81f2-4188-8c16-0c56987fecdd
    type: collection
    task:
      id: 987cbeb0-81f2-4188-8c16-0c56987fecdd
      version: -1
      name: Select a script to execute
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Fidelis Analyst
      subject:
        simple: Select script to execute
      body:
        simple: Use the link below to select the script to execute against ${incident.endpointname}
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "Yes"
      - "No"
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Select the script to execute against "${incident.endpointname}"
        required: true
        gridcolumns: []
        defaultrows: []
        type: multiSelect
        options:
        - ""
        - Process List
        - Service List
        - Isolate Endpoint
        fieldassociated: ""
        placeholder: ""
        tooltip: Select 1 more tasks to execute
      title: Script Selection
      description: Which script should be executed?
      sender: ""
      expired: false
      totalanswers: 0
  "21":
    id: "21"
    taskid: df42e662-aaec-456a-8c98-3a7dd24a9624
    type: condition
    task:
      id: df42e662-aaec-456a-8c98-3a7dd24a9624
      version: -1
      name: Does this incident require script execution?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "13"
      "Yes":
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -160,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Fidelis Analyst
      subject:
        simple: Does incident ID ${incident.id} require script execution?
      body:
        simple: |-
          A new incident named "${incident.name}" was created. It affects the endpoint "${incident.endpointname}".

          The link to the incident is here: ${demistoUrls.investigation}

          Would you like to execute a script against this endpoint?
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "Yes"
      - "No"
  "22":
    id: "22"
    taskid: 5c194225-fb74-4201-8953-78423a43d008
    type: regular
    task:
      id: 5c194225-fb74-4201-8953-78423a43d008
      version: -1
      name: Run Service List Script
      description: Attempts to retrieve the live running processes from an endpoint.
      scriptName: FidelisElevateEndpointGetServices
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      filter: {}
      updateContext: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: 7502d911-44c8-4ee1-8e0d-c4883ce39a34
    type: condition
    task:
      id: 7502d911-44c8-4ee1-8e0d-c4883ce39a34
      version: -1
      name: Process List?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "25"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: Script Selection.Answers.0
            iscontext: true
          right:
            value:
              simple: Process List
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "24":
    id: "24"
    taskid: 707e8473-93b3-412f-8c1f-ad6fe3bb23e3
    type: condition
    task:
      id: 707e8473-93b3-412f-8c1f-ad6fe3bb23e3
      version: -1
      name: Isolate?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: Script Selection.Answers.0
            iscontext: true
          right:
            value:
              simple: Isolate Endpoint
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "25":
    id: "25"
    taskid: 20c98017-9af4-4e6b-87d2-4883bc31e13d
    type: condition
    task:
      id: 20c98017-9af4-4e6b-87d2-4883bc31e13d
      version: -1
      name: Service List?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "22"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: Script Selection.Answers.0
            iscontext: true
          right:
            value:
              simple: Process List
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2485,
        "width": 702.5,
        "x": -160,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
