id: 68bb9ab1-a72e-446d-8023-72f73b25d063
version: 92
name: Fidelis Elevate Endpoint - Default Playbook
description: This is the default playbook for Fidelis Elevate Endpoint Incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
    type: start
    task:
      id: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: fd32ea2b-15fd-4e54-8048-93be5c241a9a
    type: playbook
    task:
      id: fd32ea2b-15fd-4e54-8048-93be5c241a9a
      version: -1
      name: Fidelis Elevate Endpoint Enrichment
      description: This playbook will attempt to gather event data for the alert (if
        it exists and the alert does not already have event data). It will also assign
        an incident type based on the event data it finds.
      playbookName: Fidelis Elevate Endpoint Enrichment
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
    type: title
    task:
      id: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: dff5635d-37ee-4dc4-8c13-1fbf50f35d7b
    type: condition
    task:
      id: dff5635d-37ee-4dc4-8c13-1fbf50f35d7b
      version: -1
      name: Manually Investigate
      description: |-
        # Investigate

        All tasks as part of this incidents playbook have been completed.

        When this task is completed the incident will close.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Complete:
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: e10c55bb-feec-47e3-87c0-cc30685f7df6
    type: regular
    task:
      id: e10c55bb-feec-47e3-87c0-cc30685f7df6
      version: -1
      name: Close Incident
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id:
        simple: ${incident.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: a1cf3e20-1db1-4980-82b9-6a49d0e7440a
    type: condition
    task:
      id: a1cf3e20-1db1-4980-82b9-6a49d0e7440a
      version: -1
      name: Delete Fidelis Alert?
      description: |-
        # Delete Fidelis Alert

        Please select whether you would like to delete the alert from the FIdelis Elevate Endpoint Platform.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      DO NOT delete:
      - "14"
      Delete:
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 87125a20-b1f9-4390-8c1f-61511dd79d62
    type: regular
    task:
      id: 87125a20-b1f9-4390-8c1f-61511dd79d62
      version: -1
      name: FidelisElevateEndpointDeleteAlert
      description: Attempts to delete an alert from the Fidelis Endpoint Platform
      scriptName: FidelisElevateEndpointDeleteAlert
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: 03025cac-9746-46b0-825a-062fb67b57cc
    type: regular
    task:
      id: 03025cac-9746-46b0-825a-062fb67b57cc
      version: -1
      name: Set continuation flag
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsComplete
      value:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "24":
    id: "24"
    taskid: 071fc3a6-ea3e-417f-873b-a631558cc966
    type: regular
    task:
      id: 071fc3a6-ea3e-417f-873b-a631558cc966
      version: -1
      name: Delete script data
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsComplete
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "25":
    id: "25"
    taskid: 08215795-8c46-415d-828f-097f45b6790b
    type: regular
    task:
      id: 08215795-8c46-415d-828f-097f45b6790b
      version: -1
      name: Delete script data
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsCurrent
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "26":
    id: "26"
    taskid: c08837a6-4f7a-4720-8e76-bdfd0e507a04
    type: regular
    task:
      id: c08837a6-4f7a-4720-8e76-bdfd0e507a04
      version: -1
      name: Ask user via email
      description: Ask a user a question via email and process the reply directly
        into the investigation.
      scriptName: EmailAskUser
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      additionalOptions: {}
      attachIds: {}
      bcc: {}
      bodyType:
        simple: text
      cc: {}
      email: {}
      message:
        simple: "A new incident named \"${incident.name}\" was created with ID ${incident.id}.\n\nYou
          can view the incident here: ${demistoUrls.investigation}.\n\nDoes this incident
          require script execution against \n\"${incident.endpointname}\"?"
      option1:
        simple: "Yes"
      option2:
        simple: "No"
      persistent:
        simple: "false"
      playbookTaskID: {}
      replyAddress:
        simple: demisto@dfir.co.uk
      replyEntriesTag:
        simple: userResponse
      retries: {}
      roles:
        simple: Fidelis Analyst
      subject:
        simple: Script execution for incident${incident.id}
      task:
        simple: "27"
      using:
        simple: Demisto Sender
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: true
    timertriggers: []
    ignoreworker: false
  "27":
    id: "27"
    taskid: f6a82899-b550-46fd-8b82-ee0555dde8da
    type: condition
    task:
      id: f6a82899-b550-46fd-8b82-ee0555dde8da
      version: -1
      name: Execute a script?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "13"
      "yes":
      - "29"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "28":
    id: "28"
    taskid: 433a30d2-4f70-47b1-81da-3d52b4fa7bbe
    type: playbook
    task:
      id: 433a30d2-4f70-47b1-81da-3d52b4fa7bbe
      version: -1
      name: Fidelis Elevate Endpoint Execute Script
      description: This script will obtain a list of available scripts and their options.
        It will then present the user with an option of which script can be executed
        and the answers that are required.
      playbookName: Fidelis Elevate Endpoint Execute Script
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      emailResults:
        simple: "True"
      requester:
        simple: ${incident.submitter}
    separatecontext: false
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: Fidelis.Endpoint.Alert.ScriptsComplete
            iscontext: true
          right:
            value:
              simple: "true"
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "29":
    id: "29"
    taskid: b75b31fc-eece-4caf-86c8-380b31cdb060
    type: regular
    task:
      id: b75b31fc-eece-4caf-86c8-380b31cdb060
      version: -1
      name: FidelisElevateEndpointGetScripts
      scriptName: FidelisElevateEndpointGetScripts
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -60,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "27_29_yes": 0.87
    },
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 715,
        "x": -60,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
