id: e16a2c2e-09bf-4607-82c2-f249f9dcf5fe
version: 80
name: Fidelis Elevate Endpoint Execute Script
description: This script will obtain a list of available scripts and their options.
  It will then present the user with an option of which script can be executed and
  the answers that are required.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6365e806-3f7a-4013-8c1e-d71b3bb03547
    type: start
    task:
      id: 6365e806-3f7a-4013-8c1e-d71b3bb03547
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 18ddeb02-1e94-4cfb-8ba0-546a68737781
    type: regular
    task:
      id: 18ddeb02-1e94-4cfb-8ba0-546a68737781
      version: -1
      name: Get a list of tasks that are available
      scriptName: FidelisElevateEndpointGetScripts
      type: regular
      iscommand: false
      brand: Fidelis Elevate Endpoint
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: a1b6d11c-4ad3-418a-8de1-f6c6850607c5
    type: collection
    task:
      id: a1b6d11c-4ad3-418a-8de1-f6c6850607c5
      version: -1
      name: Select Task
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Fidelis Analyst
      subject:
        simple: Select a task
      body:
        complex:
          root: Fidelis
          accessor: Endpoint.Scripts
          transformers:
          - operator: join
            args:
              separator:
                value:
                  simple: |2+

          - operator: concat
            args:
              prefix:
                value:
                  simple: "Please select the ID from the list below and paste it into
                    the web form:\n \n \n "
              suffix:
                value:
                  simple: " \n \nUse the web link below to paste the ID:\n \n \n"
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Please enter the task ID to run
        required: true
        gridcolumns: []
        defaultrows: []
        type: shortText
        options:
        - "Yes"
        - "No"
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
      title: Select Task to Run
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
  "6":
    id: "6"
    taskid: 70b079bf-25e9-46c9-829c-e89b9958101f
    type: regular
    task:
      id: 70b079bf-25e9-46c9-829c-e89b9958101f
      version: -1
      name: fidelis-edr-get-script-questions
      description: Retrieves a list of questions that need answering for a Fidelis
        script
      script: Fidelis Elevate Endpoint|||fidelis-edr-get-script-questions
      type: regular
      iscommand: true
      brand: Fidelis Elevate Endpoint
    scriptarguments:
      scriptId:
        complex:
          root: Select Task to Run
          accessor: Answers.0
          transformers:
          - operator: replace
            args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: ' '
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 5b566b0e-216b-4b49-8fd8-c4412b679ce4
    type: regular
    task:
      id: 5b566b0e-216b-4b49-8fd8-c4412b679ce4
      version: -1
      name: Delete Scripts Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Fidelis.Endpoint.Scripts
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 705,
        "width": 380,
        "x": 450,
        "y": -240
      }
    }
  }
inputs: []
outputs: []
