id: 68bb9ab1-a72e-446d-8023-72f73b25d063
version: 54
name: Fidelis Elevate Endpoint - Default Playbook
description: This is the default playbook for Fidelis Elevate Endpoint Incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
    type: start
    task:
      id: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: fd32ea2b-15fd-4e54-8048-93be5c241a9a
    type: playbook
    task:
      id: fd32ea2b-15fd-4e54-8048-93be5c241a9a
      version: -1
      name: Fidelis Elevate Endpoint Enrichment
      description: This playbook will attempt to gather event data for the alert (if
        it exists and the alert does not already have event data). It will also assign
        an incident type based on the event data it finds.
      playbookName: Fidelis Elevate Endpoint Enrichment
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
    type: title
    task:
      id: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: c03ea329-e256-49fe-85d2-144b210b5f90
    type: condition
    task:
      id: c03ea329-e256-49fe-85d2-144b210b5f90
      version: -1
      name: Investigate
      description: |-
        # Investigate

        All tasks as part of this incidents playbook have been completed.

        When this task is completed the incident will close.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Complete:
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: e10c55bb-feec-47e3-87c0-cc30685f7df6
    type: regular
    task:
      id: e10c55bb-feec-47e3-87c0-cc30685f7df6
      version: -1
      name: Close Incident
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id:
        simple: ${incident.id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: a1cf3e20-1db1-4980-82b9-6a49d0e7440a
    type: condition
    task:
      id: a1cf3e20-1db1-4980-82b9-6a49d0e7440a
      version: -1
      name: Delete Fidelis Alert?
      description: |-
        # Delete Fidelis Alert

        Please select whether you would like to delete the alert from the FIdelis Elevate Endpoint Platform.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      DO NOT delete:
      - "14"
      Delete:
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 87125a20-b1f9-4390-8c1f-61511dd79d62
    type: regular
    task:
      id: 87125a20-b1f9-4390-8c1f-61511dd79d62
      version: -1
      name: FidelisElevateEndpointDeleteAlert
      description: Attempts to delete an alert from the Fidelis Endpoint Platform
      scriptName: FidelisElevateEndpointDeleteAlert
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 8b7a8bf5-c4d9-470c-8574-451f7b9e44a2
    type: condition
    task:
      id: 8b7a8bf5-c4d9-470c-8574-451f7b9e44a2
      version: -1
      name: Does this incident require script execution?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "No":
      - "13"
      "Yes":
      - "23"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Fidelis Analyst
      subject:
        simple: Does incident ID ${incident.id} require script execution?
      body:
        simple: |-
          A new incident named "${incident.name}" was created. It affects the endpoint "${incident.endpointname}".

          The link to the incident is here: ${demistoUrls.investigation}

          Would you like to execute a script against this endpoint?
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "Yes"
      - "No"
  "22":
    id: "22"
    taskid: 828165ea-5059-45e2-88ef-4af1f55cf81f
    type: playbook
    task:
      id: 828165ea-5059-45e2-88ef-4af1f55cf81f
      version: -1
      name: Fidelis Elevate Endpoint Execute Script
      description: This script will obtain a list of available scripts and their options.
        It will then present the user with an option of which script can be executed
        and the answers that are required.
      playbookName: Fidelis Elevate Endpoint Execute Script
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "24"
    separatecontext: false
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: Fidelis.Endpoint.Alert.ScriptsComplete
            iscontext: true
          right:
            value:
              simple: "true"
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: 03025cac-9746-46b0-825a-062fb67b57cc
    type: regular
    task:
      id: 03025cac-9746-46b0-825a-062fb67b57cc
      version: -1
      name: Set continuation flag
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsComplete
      value:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "24":
    id: "24"
    taskid: 071fc3a6-ea3e-417f-873b-a631558cc966
    type: regular
    task:
      id: 071fc3a6-ea3e-417f-873b-a631558cc966
      version: -1
      name: Delete script data
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsComplete
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "25":
    id: "25"
    taskid: 08215795-8c46-415d-828f-097f45b6790b
    type: regular
    task:
      id: 08215795-8c46-415d-828f-097f45b6790b
      version: -1
      name: Delete script data
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all: {}
      index: {}
      key:
        simple: Fidelis.Endpoint.Alert.ScriptsCurrent
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "21_23_Yes": 0.9
    },
    "paper": {
      "dimensions": {
        "height": 1960,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
