id: 68bb9ab1-a72e-446d-8023-72f73b25d063
version: 32
name: Fidelis Elevate Endpoint - Default Playbook
description: This is the default playbook for Fidelis Elevate Endpoint Incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
    type: start
    task:
      id: 019203a5-8f4e-43b1-8883-b3a7bd9fe392
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": -240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: fd32ea2b-15fd-4e54-8048-93be5c241a9a
    type: playbook
    task:
      id: fd32ea2b-15fd-4e54-8048-93be5c241a9a
      version: -1
      name: Fidelis Elevate Endpoint Enrichment
      description: This playbook will attempt to gather event data for the alert (if
        it exists and the alert does not already have event data). It will also assign
        an incident type based on the event data it finds.
      playbookName: Fidelis Elevate Endpoint Enrichment
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": -135
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: ec8249c1-84ba-40db-8088-bd8b4b08ca5f
    type: playbook
    task:
      id: ec8249c1-84ba-40db-8088-bd8b4b08ca5f
      version: -1
      name: Fidelis Elevate Endpoint Create CEF Alert
      description: This playbook maps fields from a Fidelis Endpoint Alert and Event
        to common CEF fields.
      playbookName: Fidelis Elevate Endpoint Create CEF Alert
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 0
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: a245514e-d0f8-43fd-82da-42afadbbc1fc
    type: regular
    task:
      id: a245514e-d0f8-43fd-82da-42afadbbc1fc
      version: -1
      name: Send message
      description: Attempts to send data using the Python socket library
      scriptName: SendNetworkData
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      data:
        simple: <134> ${CEF Alert}
      header: {}
      host:
        simple: 10.0.0.240
      port:
        simple: "514"
      protocol:
        simple: UDP
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
    type: title
    task:
      id: 35fc7ac3-33f2-4436-8c64-6c8d2c5be2d1
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -390,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 9141e555-233e-429d-89da-63f9ac154c38
    type: condition
    task:
      id: 9141e555-233e-429d-89da-63f9ac154c38
      version: -1
      name: Check response
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      isolate:
      - "7"
    separatecontext: false
    conditions:
    - label: isolate
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Execute a script?.Answers.0
            iscontext: true
          right:
            value:
              simple: Isolate Endpoint
    view: |-
      {
        "position": {
          "x": 50,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: c1129fab-eed9-48c3-8b3f-0fc87cd96031
    type: playbook
    task:
      id: c1129fab-eed9-48c3-8b3f-0fc87cd96031
      version: -1
      name: Fidelis Elevate Endpoint Script - Isolate Endpoint
      description: This script will request authorisation to execute an endpoint isolation
        script using Fidelis Elevate Endpoint
      playbookName: Fidelis Elevate Endpoint Script - Isolate Endpoint
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      justification:
        simple: ${Execute a script?.Answers.1}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 530,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: b7aca79e-5753-4f8f-82bd-5191aec7aabe
    type: regular
    task:
      id: b7aca79e-5753-4f8f-82bd-5191aec7aabe
      version: -1
      name: AssignAnalystToIncident
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      assignBy: {}
      email: {}
      roles:
        simple: Fidelis Analyst
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 8b20b7bf-634c-4136-8891-dc6989e61192
    type: collection
    task:
      id: 8b20b7bf-634c-4136-8891-dc6989e61192
      version: -1
      name: Please select a task
      description: |-
        # Select a script

        Please reply with a script to run. Or, if you don't want to execute script, simply reply "no".

        Possible script options are:

        - Isolate Endpoint
        - Process List
        - Task List
        - Service List
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 405
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Analyst
      subject:
        simple: Script execution for new incident
      body: {}
      methods:
      - slack
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Which script would you like to execute?
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - None
        - Isolate Endpoint
        fieldassociated: ""
        placeholder: ""
        tooltip: Please select which script (if any) you would like to execute?
      - id: "1"
        label: ""
        labelarg:
          simple: Please provide a justification for the script (if any selected)
        required: false
        gridcolumns: []
        defaultrows: []
        type: shortText
        options: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
      title: Execute a script?
      description: A new incident may require script execution
      sender: ""
      expired: false
      totalanswers: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 1300,
        "x": -390,
        "y": -240
      }
    }
  }
inputs: []
outputs: []
