id: e7ac9021-96ee-451c-88fa-a2a027f5f20b
version: 316
name: Fidelis Elevate Endpoint Enrichment
description: This playbook will attempt to gather event data for the alert (if it
  exists and the alert does not already have event data). It will also assign an incident
  type based on the event data it finds.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9be60df9-5ff1-4c8a-86fe-824530ba4d8d
    type: start
    task:
      id: 9be60df9-5ff1-4c8a-86fe-824530ba4d8d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1880,
          "y": 100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 36e92861-f80d-4fd1-879f-13b7bb0233fe
    type: condition
    task:
      id: 36e92861-f80d-4fd1-879f-13b7bb0233fe
      version: -1
      name: Is there an alert ID?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "84"
      "yes":
      - "66"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: incident
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: incident.sourceBrand
                      iscontext: true
                    right:
                      value:
                        simple: Fidelis Elevate Endpoint
                accessor: labels.Id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1880,
          "y": 250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 6b87887c-ca5c-4d05-85fe-fefdc16b80fe
    type: title
    task:
      id: 6b87887c-ca5c-4d05-85fe-fefdc16b80fe
      version: -1
      name: Populate incident fields
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "83"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 705
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "66":
    id: "66"
    taskid: a32dbc64-8a74-4d63-805e-409f7cd97ce7
    type: regular
    task:
      id: a32dbc64-8a74-4d63-805e-409f7cd97ce7
      version: -1
      name: Get Alert Details
      description: Retrieves the details of an alert
      scriptName: FidelisElevateEndpointGetAlertDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "82"
    scriptarguments:
      alertId:
        complex:
          root: incident
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: incident.sourceBrand
                iscontext: true
              right:
                value:
                  simple: Fidelis Elevate Endpoint
          accessor: labels.Id
    reputationcalc: 3
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "70":
    id: "70"
    taskid: e8a52fe4-a331-4888-83a0-4621e61cd952
    type: regular
    task:
      id: e8a52fe4-a331-4888-83a0-4621e61cd952
      version: -1
      name: Get Endpoint Details
      description: Attempts to refresh the endpoint details associated with the incident
      scriptName: FidelisElevateEndpointRefreshEndpointDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "72"
    scriptarguments:
      hostname:
        complex:
          root: incident
          filters:
          - - operator: isExists
              left:
                value:
                  simple: incident.labels.Target
                iscontext: true
          accessor: labels.Target
    reputationcalc: 1
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "71":
    id: "71"
    taskid: 9e8bcef6-1f52-40f2-809d-1ccc4dee1a78
    type: playbook
    task:
      id: 9e8bcef6-1f52-40f2-809d-1ccc4dee1a78
      version: -1
      name: Fidelis Elevate Endpoint Get Event for Alert
      description: Attempts to look up the event data associated with an alert generated
        by Fidelis Elevate Endpoint
      playbookName: Fidelis Elevate Endpoint Get Event for Alert
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      alertId:
        complex:
          root: incident
          filters:
          - - operator: isExists
              left:
                value:
                  simple: incident.labels.Id
                iscontext: true
          accessor: labels.Id
      sleepTime:
        simple: "5"
    separatecontext: false
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: Fidelis.Endpoint.Alert.Event Found
            iscontext: true
          right:
            value:
              simple: "True"
        - operator: greaterThanOrEqual
          left:
            value:
              simple: Fidelis.Endpoint.Alert.Event Retries
            iscontext: true
          right:
            value:
              simple: "5"
        - operator: isTrue
          left:
            value:
              simple: Found Event
            iscontext: true
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "72":
    id: "72"
    taskid: 6f6789ae-3a22-4b3d-8b41-9fbda4f0c83c
    type: regular
    task:
      id: 6f6789ae-3a22-4b3d-8b41-9fbda4f0c83c
      version: -1
      name: Set the event collect retry count to 0
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "71"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.Event Retries
      value:
        simple: "0"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "82":
    id: "82"
    taskid: df14cb41-d115-486e-82e9-0500d52de786
    type: regular
    task:
      id: df14cb41-d115-486e-82e9-0500d52de786
      version: -1
      name: Get Platform Details
      script: '|||fidelis-edr-get-platform-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "70"
    reputationcalc: 1
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "83":
    id: "83"
    taskid: 48a193ca-35f3-4cd3-8bab-5fed9b48f867
    type: regular
    task:
      id: 48a193ca-35f3-4cd3-8bab-5fed9b48f867
      version: -1
      name: FidelisElevateEndpointPopulateProcessFields
      scriptName: FidelisElevateEndpointIncidentFields
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "84"
    reputationcalc: 3
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "84":
    id: "84"
    taskid: 784d3fc5-867f-4d6f-8a22-93efd3b0b277
    type: title
    task:
      id: 784d3fc5-867f-4d6f-8a22-93efd3b0b277
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2350,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 865,
        "width": 1870,
        "x": 860,
        "y": 100
      }
    }
  }
inputs: []
outputs: []
