id: e7ac9021-96ee-451c-88fa-a2a027f5f20b
version: 323
name: Fidelis Elevate Endpoint Enrichment
description: This playbook will attempt to gather event data for the alert (if it
  exists and the alert does not already have event data). It will also assign an incident
  type based on the event data it finds.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9be60df9-5ff1-4c8a-86fe-824530ba4d8d
    type: start
    task:
      id: 9be60df9-5ff1-4c8a-86fe-824530ba4d8d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1880,
          "y": 100
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: b54c1113-593d-4315-8942-8a92fedd461c
    type: condition
    task:
      id: b54c1113-593d-4315-8942-8a92fedd461c
      version: -1
      name: Is there an alert ID?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "84"
      "yes":
      - "66"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: incident.fidelisendpointalertid
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1880,
          "y": 250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 6b87887c-ca5c-4d05-85fe-fefdc16b80fe
    type: title
    task:
      id: 6b87887c-ca5c-4d05-85fe-fefdc16b80fe
      version: -1
      name: Populate incident fields
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "83"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 705
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "66":
    id: "66"
    taskid: 9f7947f1-c12b-4fa8-86df-ffff157ef26b
    type: regular
    task:
      id: 9f7947f1-c12b-4fa8-86df-ffff157ef26b
      version: -1
      name: Get Alert Details
      description: Retrieves the details of an alert
      scriptName: FidelisElevateEndpointGetAlertDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "82"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "70":
    id: "70"
    taskid: 868b7560-12c2-44d7-8ac1-84930532ed4b
    type: regular
    task:
      id: 868b7560-12c2-44d7-8ac1-84930532ed4b
      version: -1
      name: Get Endpoint Details
      description: Attempts to refresh the endpoint details associated with the incident
      scriptName: FidelisElevateEndpointRefreshEndpointDetails
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "72"
    scriptarguments:
      hostname:
        simple: ${incident.endpointname}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "71":
    id: "71"
    taskid: 4dca30ec-a821-42f2-8f1e-a23124a97966
    type: playbook
    task:
      id: 4dca30ec-a821-42f2-8f1e-a23124a97966
      version: -1
      name: Fidelis Elevate Endpoint Get Event for Alert
      description: Attempts to look up the event data associated with an alert generated
        by Fidelis Elevate Endpoint
      playbookName: Fidelis Elevate Endpoint Get Event for Alert
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      alertId:
        simple: ${incident.fidelisendpointalertid}
      sleepTime:
        simple: "5"
    separatecontext: false
    loop:
      iscommand: false
      builtincondition:
      - - operator: isEqualString
          left:
            value:
              simple: Fidelis.Endpoint.Alert.Event Found
            iscontext: true
          right:
            value:
              simple: "True"
        - operator: greaterThanOrEqual
          left:
            value:
              simple: Fidelis.Endpoint.Alert.Event Retries
            iscontext: true
          right:
            value:
              simple: "5"
        - operator: isTrue
          left:
            value:
              simple: Found Event
            iscontext: true
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "72":
    id: "72"
    taskid: c59742c4-7c21-4484-8445-a4f4ce677030
    type: regular
    task:
      id: c59742c4-7c21-4484-8445-a4f4ce677030
      version: -1
      name: Set the event collect retry count to 0
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "71"
    scriptarguments:
      append:
        simple: "false"
      key:
        simple: Fidelis.Endpoint.Alert.Event Retries
      value:
        simple: "0"
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "82":
    id: "82"
    taskid: facb4c2f-90d9-4678-8981-21489caea783
    type: regular
    task:
      id: facb4c2f-90d9-4678-8981-21489caea783
      version: -1
      name: Get Platform Details
      script: '|||fidelis-edr-get-platform-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "70"
    reputationcalc: 1
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1290,
          "y": 470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "83":
    id: "83"
    taskid: 191cbe89-f572-4d32-8c48-3620e2a95e0b
    type: regular
    task:
      id: 191cbe89-f572-4d32-8c48-3620e2a95e0b
      version: -1
      name: Populate incident fields
      scriptName: FidelisElevateEndpointIncidentFields
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "84"
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "84":
    id: "84"
    taskid: fb3033d4-9191-4ccf-8b1d-15e06759afab
    type: title
    task:
      id: fb3033d4-9191-4ccf-8b1d-15e06759afab
      version: -1
      name: User assignment
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "85"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2030,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "85":
    id: "85"
    taskid: 7c3ad851-3573-443a-80a8-40f54ab6fb82
    type: regular
    task:
      id: 7c3ad851-3573-443a-80a8-40f54ab6fb82
      version: -1
      name: AssignAnalystToIncident
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "86"
    scriptarguments:
      assignBy:
        simple: machine-learning
      email: {}
      roles:
        simple: Analyst
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2590,
          "y": 565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "86":
    id: "86"
    taskid: 3b848f50-e181-4ecf-8216-962489fdd7c4
    type: title
    task:
      id: 3b848f50-e181-4ecf-8216-962489fdd7c4
      version: -1
      name: Complete
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2590,
          "y": 855
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1005,
        "width": 2110,
        "x": 860,
        "y": 100
      }
    }
  }
inputs: []
outputs: []
