id: 8cbdf195-4307-4701-810d-3dd58bb73f74
version: 37
rolename:
- Administrator
- Fidelis Super Analyst
name: Fidelis Elevate Endpoint Script - Isolate Endpoint
description: This script will request authorisation to execute an endpoint isolation
  script using Fidelis Elevate Endpoint
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 391a712a-621a-4f0d-8b4a-fa15b629b41b
    type: start
    task:
      id: 391a712a-621a-4f0d-8b4a-fa15b629b41b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 2226880d-1a08-4187-88f9-a5b7d9edc0c3
    type: condition
    task:
      id: 2226880d-1a08-4187-88f9-a5b7d9edc0c3
      version: -1
      name: Is there an owner assigned?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "21"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: IncidentOwner.email
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": -450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: f75ad23f-007f-470a-8fe2-defb685ffee1
    type: collection
    task:
      id: f75ad23f-007f-470a-8fe2-defb685ffee1
      version: -1
      name: Request for more information
      description: |-
        # Justification

        Please enter your justification comments in the comments and select "Submit"
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 130,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ${incident.owner}
      subject:
        simple: Justification
      body: null
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: Justification
        required: true
        gridcolumns: []
        defaultrows: []
        type: shortText
        options: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
      title: Justification
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
  "6":
    id: "6"
    taskid: c9f4de7a-1212-4331-8adb-d0c4f391f5ec
    type: condition
    task:
      id: c9f4de7a-1212-4331-8adb-d0c4f391f5ec
      version: -1
      name: Provide a justification
      description: Please provide a justification for the isolation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Deny:
      - "8"
    separatecontext: false
    defaultassigneecomplex:
      simple: ${incident.owner}
    restrictedcompletion: true
    view: |-
      {
        "position": {
          "x": 130,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 5d1a151a-7c7e-4c51-8464-e20680e192b8
    type: regular
    task:
      id: 5d1a151a-7c7e-4c51-8464-e20680e192b8
      version: -1
      name: Fail the playbook
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Permission denied by "${Authorisation.Answers.name}" to Isolate the
          endpoint
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 820,
          "y": 780
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 5566eb3b-c4a0-45fd-8199-3ed214aad924
    type: regular
    task:
      id: 5566eb3b-c4a0-45fd-8199-3ed214aad924
      version: -1
      name: FidelisElevateEndpointIsolateEndpoint
      script: '|||fidelis-edr-isolate-endpoint'
      type: regular
      iscommand: true
      brand: ""
    scriptarguments:
      additionalIPs: {}
      hostname:
        simple: ${incident.endpointname}
      timeout: {}
      updateContext:
        simple: "False"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1170,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 75582e3a-fb24-4921-8481-4adbbdfa5dbe
    type: regular
    task:
      id: 75582e3a-fb24-4921-8481-4adbbdfa5dbe
      version: -1
      name: ExposeIncidentOwner
      description: Expose the incident owner into IncidentOwner context key
      scriptName: ExposeIncidentOwner
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    reputationcalc: 1
    results:
    - IncidentOwner
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 4bf3f0f0-b7e7-4033-80c9-7a3843fe1f28
    type: regular
    task:
      id: 4bf3f0f0-b7e7-4033-80c9-7a3843fe1f28
      version: -1
      name: AssignAnalystToIncident
      description: |-
        Assign analyst to incident.
        By default,  the analyst is picked randomly from the available users, according to the provided roles (if no roles provided, will fetch all users).
        Otherwise, the analyst will be picked according to the 'assignBy' arguments.
        machine-learning: DBot will calculated and decide who is the best analyst for the job.
        top-user: The user that is most commonly owns this type of incident
        less-busy-user: The less busy analyst will be picked to be the incident owner.
        online: The analyst is picked randomly from all online analysts, according to the provided roles (if no roles provided, will fetch all users).
        current: The user that executed the command
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      assignBy:
        simple: machine-learning
      email: {}
      roles:
        simple: Analyst
      username: {}
    reputationcalc: 1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -20,
          "y": -280
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 356f47e7-bb2d-468e-8bed-a475afaeb28b
    type: condition
    task:
      id: 356f47e7-bb2d-468e-8bed-a475afaeb28b
      version: -1
      name: Authorise Isolate Endpoint Script
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Authorise:
      - "11"
      Deny:
      - "8"
      Require further information:
      - "5"
    separatecontext: false
    sla:
      hours: 0
      days: 1
      weeks: 0
    slareminder:
      hours: 2
      days: 0
      weeks: 0
    view: |-
      {
        "position": {
          "x": 450,
          "y": -120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Fidelis Super Analyst
      subject:
        simple: Authorise Isolate Endpoint Script
      body:
        simple: Authorise "Isolate Endpoint" script on ${incident.endpointname}
      methods:
      - email
      - slack
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - Authorise
      - Deny
      - Require further information
view: |-
  {
    "linkLabelsPosition": {
      "3_21_yes": 0.9
    },
    "paper": {
      "dimensions": {
        "height": 1845,
        "width": 1570,
        "x": -20,
        "y": -740
      }
    }
  }
inputs:
- key: justification
  value: {}
  required: false
  description: ""
outputs: []
