id: 9c3728f8-e683-4544-8c2e-790b89de671b
version: 2
name: OPNsense Remove IP from List
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: afe1b75d-2b6b-4ef0-8099-f339b9477981
    type: start
    task:
      id: afe1b75d-2b6b-4ef0-8099-f339b9477981
      version: -1
      name: ""
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
